export type { Transport, RequestHandler } from './transport.js'
export type { ExtensionContext, WindowApi, WorkspaceApi } from './extension-context.js'
export { createExtensionContext } from './extension-context.js'
export { createIpcTransport } from './ipc-adapter.js'
export { createGrpcTransport } from './grpc-adapter.js'
export { coalesceLastWins } from './coalesce.js'
