import type { RegistryIndex } from '@nodalcore/registry-client'

function makeIcon(initials: string, bg: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="${bg}"/><text x="32" y="43" font-family="monospace,system-ui" font-size="22" font-weight="bold" text-anchor="middle" fill="white">${initials}</text></svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

export const MOCK_REGISTRY: RegistryIndex = {
  version: '1',
  updatedAt: '2026-04-20T00:00:00.000Z',
  plugins: [
    {
      id: 'com.nodalcore.usb-oscilloscope',
      name: 'USB Oscilloscope',
      version: '1.2.0',
      description:
        'Two-channel USB oscilloscope with up to 100 MHz bandwidth. Capture and visualize waveforms in real time with configurable trigger modes.',
      icon: makeIcon('OS', '#0ea5e9'),
      type: 'device-bridge',
      connectionType: 'usb',
      permissions: ['usb'],
      tags: ['oscilloscope', 'waveform', 'usb', 'measurement'],
      author: { name: 'NodalCore Team' },
      repository: 'https://github.com/nodalcore/usb-oscilloscope',
      manifestUrl: '',
      installs: 1284,
      updatedAt: '2026-04-10T00:00:00.000Z',
    },
    {
      id: 'com.nodalcore.temperature-sensor',
      name: 'Temperature & Humidity Sensor',
      version: '0.9.4',
      description:
        'Supports DHT11, DHT22, and SHT31 sensors over serial. Logs readings at configurable intervals and provides live chart output.',
      icon: makeIcon('TH', '#f97316'),
      type: 'device-bridge',
      connectionType: 'serial',
      permissions: ['serial'],
      tags: ['temperature', 'humidity', 'dht22', 'serial', 'environment'],
      author: { name: 'SensorLab' },
      repository: 'https://github.com/nodalcore/temp-humidity',
      manifestUrl: '',
      installs: 3871,
      updatedAt: '2026-03-28T00:00:00.000Z',
    },
    {
      id: 'com.nodalcore.stepper-controller',
      name: 'Stepper Motor Controller',
      version: '2.0.1',
      description:
        'Precise stepper motor control over serial. Supports microstepping, acceleration ramps, and multi-axis coordination for CNC and robotics.',
      icon: makeIcon('SM', '#22c55e'),
      type: 'device-bridge',
      connectionType: 'serial',
      permissions: ['serial'],
      tags: ['stepper', 'motor', 'cnc', 'robotics', 'serial'],
      author: { name: 'MotionLab' },
      repository: 'https://github.com/nodalcore/stepper-controller',
      manifestUrl: '',
      installs: 652,
      updatedAt: '2026-04-01T00:00:00.000Z',
    },
    {
      id: 'com.nodalcore.ble-heart-rate',
      name: 'BLE Heart Rate Monitor',
      version: '1.0.3',
      description:
        'Connects to any Bluetooth LE heart rate monitor (GATT standard). Streams BPM and RR intervals with configurable alert thresholds.',
      icon: makeIcon('HR', '#ec4899'),
      type: 'device-bridge',
      connectionType: 'bluetooth',
      permissions: ['bluetooth'],
      tags: ['ble', 'heart-rate', 'biometrics', 'bluetooth', 'health'],
      author: { name: 'BioSense' },
      repository: 'https://github.com/nodalcore/ble-heart-rate',
      manifestUrl: '',
      installs: 2109,
      updatedAt: '2026-04-15T00:00:00.000Z',
    },
    {
      id: 'com.nodalcore.can-bus-analyzer',
      name: 'CAN Bus Analyzer',
      version: '1.1.0',
      description:
        'Decode and inspect CAN bus frames from USB-CAN adapters. Filter by arbitration ID, log to CSV, and decode DBC message definitions.',
      icon: makeIcon('CA', '#6366f1'),
      type: 'device-bridge',
      connectionType: 'usb',
      permissions: ['usb'],
      tags: ['can-bus', 'automotive', 'usb', 'protocol', 'decode'],
      author: { name: 'AutoProbe' },
      repository: 'https://github.com/nodalcore/can-bus-analyzer',
      manifestUrl: '',
      installs: 415,
      updatedAt: '2026-03-14T00:00:00.000Z',
    },
    {
      id: 'com.nodalcore.signal-analyzer',
      name: 'Signal Analyzer',
      version: '0.8.2',
      description:
        'Real-time FFT and spectrogram analysis for any signal source. Configurable window functions, frequency resolution, and export to PNG or CSV.',
      icon: makeIcon('SA', '#8b5cf6'),
      type: 'standalone-tool',
      permissions: [],
      tags: ['fft', 'signal', 'spectrogram', 'analysis', 'standalone'],
      author: { name: 'DSP Works' },
      repository: 'https://github.com/nodalcore/signal-analyzer',
      manifestUrl: '',
      installs: 788,
      updatedAt: '2026-02-22T00:00:00.000Z',
    },
    {
      id: 'com.nodalcore.data-logger',
      name: 'Data Logger',
      version: '1.3.0',
      description:
        'Record data streams from any connected device to SQLite or CSV. Configurable sampling rate, compression, and automatic file rotation.',
      icon: makeIcon('DL', '#eab308'),
      type: 'standalone-tool',
      permissions: [],
      tags: ['logging', 'sqlite', 'csv', 'data', 'recording', 'standalone'],
      author: { name: 'NodalCore Team' },
      repository: 'https://github.com/nodalcore/data-logger',
      manifestUrl: '',
      installs: 5212,
      updatedAt: '2026-04-18T00:00:00.000Z',
    },
    {
      id: 'com.nodalcore.mqtt-dashboard',
      name: 'MQTT Dashboard',
      version: '2.1.0',
      description:
        'Subscribe to MQTT topics, visualize payloads as gauges or charts, and publish messages. Supports TLS and username/password authentication.',
      icon: makeIcon('MQ', '#14b8a6'),
      type: 'device-bridge',
      connectionType: 'mqtt',
      permissions: ['network'],
      tags: ['mqtt', 'iot', 'dashboard', 'tcp', 'network'],
      author: { name: 'IotBridge' },
      repository: 'https://github.com/nodalcore/mqtt-dashboard',
      manifestUrl: '',
      installs: 1673,
      updatedAt: '2026-04-05T00:00:00.000Z',
    },
  ],
}
