// Generated by apps/desktop/scripts/gen-tray-icon.mjs — placeholder tray icons.
// Replace this module (or swap to real PNG files + electron-vite asset copy) when
// real iconography is ready. tray.ts loads these via nativeImage.createFromBuffer.

export const TRAY_ICON_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAIUlEQVR4nGNIS0v7TwvMMGrwqMGjBo8aPGrwqMGjBlOGAWKFJOGm+IMLAAAAAElFTkSuQmCC'
export const TRAY_ICON_2X_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAYAAAAehFoBAAAAQUlEQVR4nO3OMREAIAwEsKp9/w5ABk8vQ/ZMkvOTeR0QbiMsLCwsLCxcRVhYWFhYWLiKsLCwsLCwcBVhYWHhZeELdueTgZnOX4sAAAAASUVORK5CYII='
export const TRAY_ICON_TEMPLATE_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAHklEQVR4nGP4TyPAMGrwqMGjBo8aPGrwqMGjBlMGAHwmiNqM5jwCAAAAAElFTkSuQmCC'
